import { NextRequest, NextResponse } from 'next/server';
import { getCollection } from '@/lib/mongodb';

export async function POST(request: NextRequest) {
  try {
    const collection = await getCollection('claims');

    // Sample dummy data
    const dummyClaims = [
      // Medications - 30 entries
      {
        id: 'claim_med_1',
        category: 'medications',
        rxNumber: 'RX-10427',
        productName: 'Metformin 500mg',
        prescriberName: 'Dr. A. Johnson',
        prescriberLicense: 'CPSO #87921',
        prescriberFax: '+1 (416) 555-1234',
        prescriberPhone: '+1 (416) 555-5678',
        dateOfPrescription: '2024-01-15',
        type: 'renewal',
        claimStatus: 'authorized',
        authorizationNumber: 'E-12345',
        authorizationStartDate: '2024-01-15',
        authorizationEndDate: '2024-12-31',
        documents: [],
        notes: [
          {
            id: 'note_1',
            text: 'Initial authorization approved',
            staffUsername: 'Admin User',
            timestamp: new Date('2024-01-16').toISOString(),
          },
        ],
        priority: false,
        createdAt: new Date('2024-01-15').toISOString(),
        updatedAt: new Date('2024-01-16').toISOString(),
      },
      {
        id: 'claim_med_2',
        category: 'medications',
        rxNumber: 'RX-10428',
        productName: 'Lantus Solostar 100u/ml',
        prescriberName: 'Dr. B. Smith',
        prescriberLicense: 'CPSO #98765',
        prescriberFax: '',
        prescriberPhone: '+1 (416) 555-9012',
        dateOfPrescription: '2024-01-20',
        type: 'new',
        claimStatus: 'case-number-open',
        authorizationNumber: '',
        authorizationStartDate: '',
        authorizationEndDate: '',
        documents: [],
        notes: [],
        priority: true,
        createdAt: new Date('2024-01-20').toISOString(),
        updatedAt: new Date('2024-01-20').toISOString(),
      },
      {
        id: 'claim_med_3',
        category: 'medications',
        rxNumber: 'RX-09821',
        productName: 'Metformin 500mg',
        prescriberName: 'Dr. A. Johnson',
        prescriberLicense: 'CPSO #87921',
        prescriberFax: '+1 (416) 555-1234',
        prescriberPhone: '+1 (416) 555-5678',
        dateOfPrescription: '2025-01-10',
        type: 'renewal',
        claimStatus: 'case-number-open',
        authorizationNumber: '',
        authorizationStartDate: '',
        authorizationEndDate: '',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2025-01-10').toISOString(),
        updatedAt: new Date('2025-01-10').toISOString(),
      },
      {
        id: 'claim_med_4',
        category: 'medications',
        rxNumber: 'RX-10429',
        productName: 'Amoxicillin 250mg',
        prescriberName: 'Dr. S. Ibrahim',
        prescriberLicense: 'CPSO #12345',
        prescriberFax: '',
        prescriberPhone: '+1 (416) 555-1111',
        dateOfPrescription: '2025-01-08',
        type: 'prior-authorization',
        claimStatus: 'new',
        authorizationNumber: '',
        authorizationStartDate: '',
        authorizationEndDate: '',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2025-01-08').toISOString(),
        updatedAt: new Date('2025-01-08').toISOString(),
      },
      {
        id: 'claim_med_5',
        category: 'medications',
        rxNumber: 'RX-10430',
        productName: 'Insulin Glargine',
        prescriberName: 'Dr. T. Okafor',
        prescriberLicense: 'CPSO #54321',
        prescriberFax: '',
        prescriberPhone: '+1 (416) 555-2222',
        dateOfPrescription: '2025-01-05',
        type: 'new',
        claimStatus: 'authorized',
        authorizationNumber: 'E-99999',
        authorizationStartDate: '2025-01-05',
        authorizationEndDate: '2026-01-05',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2025-01-05').toISOString(),
        updatedAt: new Date('2025-01-05').toISOString(),
      },
      {
        id: 'claim_med_6',
        category: 'medications',
        rxNumber: 'RX-10431',
        productName: 'Atorvastatin 20mg',
        prescriberName: 'Dr. A. Johnson',
        prescriberLicense: 'CPSO #87921',
        prescriberFax: '+1 (416) 555-1234',
        prescriberPhone: '+1 (416) 555-5678',
        dateOfPrescription: '2025-01-12',
        type: 'new',
        claimStatus: 'new',
        authorizationNumber: '',
        authorizationStartDate: '',
        authorizationEndDate: '',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2025-01-12').toISOString(),
        updatedAt: new Date('2025-01-12').toISOString(),
      },
      {
        id: 'claim_med_7',
        category: 'medications',
        rxNumber: 'RX-10432',
        productName: 'Lisinopril 10mg',
        prescriberName: 'Dr. B. Smith',
        prescriberLicense: 'CPSO #98765',
        prescriberFax: '',
        prescriberPhone: '+1 (416) 555-9012',
        dateOfPrescription: '2025-01-03',
        type: 'renewal',
        claimStatus: 'authorized',
        authorizationNumber: 'E-23456',
        authorizationStartDate: '2025-01-03',
        authorizationEndDate: '2025-07-03',
        documents: [],
        notes: [],
        priority: true,
        createdAt: new Date('2025-01-03').toISOString(),
        updatedAt: new Date('2025-01-03').toISOString(),
      },
      {
        id: 'claim_med_8',
        category: 'medications',
        rxNumber: 'RX-10433',
        productName: 'Levothyroxine 75mcg',
        prescriberName: 'Dr. C. Williams',
        prescriberLicense: 'CPSO #45678',
        prescriberFax: '+1 (416) 555-3456',
        prescriberPhone: '+1 (416) 555-9012',
        dateOfPrescription: '2025-01-07',
        type: 'renewal',
        claimStatus: 'authorized',
        authorizationNumber: 'E-34567',
        authorizationStartDate: '2025-01-07',
        authorizationEndDate: '2025-10-07',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2025-01-07').toISOString(),
        updatedAt: new Date('2025-01-07').toISOString(),
      },
      {
        id: 'claim_med_9',
        category: 'medications',
        rxNumber: 'RX-10434',
        productName: 'Amlodipine 5mg',
        prescriberName: 'Dr. D. Brown',
        prescriberLicense: 'CPSO #23456',
        prescriberFax: '',
        prescriberPhone: '+1 (416) 555-7890',
        dateOfPrescription: '2025-01-11',
        type: 'new',
        claimStatus: 'new',
        authorizationNumber: '',
        authorizationStartDate: '',
        authorizationEndDate: '',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2025-01-11').toISOString(),
        updatedAt: new Date('2025-01-11').toISOString(),
      },
      {
        id: 'claim_med_10',
        category: 'medications',
        rxNumber: 'RX-10435',
        productName: 'Omeprazole 20mg',
        prescriberName: 'Dr. E. Davis',
        prescriberLicense: 'CPSO #11223',
        prescriberFax: '+1 (416) 555-2468',
        prescriberPhone: '+1 (416) 555-1357',
        dateOfPrescription: '2025-01-09',
        type: 'prior-authorization',
        claimStatus: 'case-number-open',
        authorizationNumber: '',
        authorizationStartDate: '',
        authorizationEndDate: '',
        documents: [],
        notes: [],
        priority: true,
        createdAt: new Date('2025-01-09').toISOString(),
        updatedAt: new Date('2025-01-09').toISOString(),
      },
      {
        id: 'claim_med_11',
        category: 'medications',
        rxNumber: 'RX-10436',
        productName: 'Gabapentin 300mg',
        prescriberName: 'Dr. A. Johnson',
        prescriberLicense: 'CPSO #87921',
        prescriberFax: '+1 (416) 555-1234',
        prescriberPhone: '+1 (416) 555-5678',
        dateOfPrescription: '2025-01-04',
        type: 'new',
        claimStatus: 'authorized',
        authorizationNumber: 'E-45678',
        authorizationStartDate: '2025-01-04',
        authorizationEndDate: '2025-06-04',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2025-01-04').toISOString(),
        updatedAt: new Date('2025-01-04').toISOString(),
      },
      {
        id: 'claim_med_12',
        category: 'medications',
        rxNumber: 'RX-10437',
        productName: 'Losartan 50mg',
        prescriberName: 'Dr. B. Smith',
        prescriberLicense: 'CPSO #98765',
        prescriberFax: '',
        prescriberPhone: '+1 (416) 555-9012',
        dateOfPrescription: '2025-01-13',
        type: 'renewal',
        claimStatus: 'new',
        authorizationNumber: '',
        authorizationStartDate: '',
        authorizationEndDate: '',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2025-01-13').toISOString(),
        updatedAt: new Date('2025-01-13').toISOString(),
      },
      {
        id: 'claim_med_13',
        category: 'medications',
        rxNumber: 'RX-10438',
        productName: 'Simvastatin 20mg',
        prescriberName: 'Dr. F. Garcia',
        prescriberLicense: 'CPSO #76543',
        prescriberFax: '+1 (416) 555-3333',
        prescriberPhone: '+1 (416) 555-4444',
        dateOfPrescription: '2025-01-06',
        type: 'new',
        claimStatus: 'case-number-open',
        authorizationNumber: '',
        authorizationStartDate: '',
        authorizationEndDate: '',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2025-01-06').toISOString(),
        updatedAt: new Date('2025-01-06').toISOString(),
      },
      {
        id: 'claim_med_14',
        category: 'medications',
        rxNumber: 'RX-10439',
        productName: 'Hydrochlorothiazide 12.5mg',
        prescriberName: 'Dr. G. Martinez',
        prescriberLicense: 'CPSO #65432',
        prescriberFax: '+1 (416) 555-5555',
        prescriberPhone: '+1 (416) 555-6666',
        dateOfPrescription: '2025-01-14',
        type: 'prior-authorization',
        claimStatus: 'authorized',
        authorizationNumber: 'E-56789',
        authorizationStartDate: '2025-01-14',
        authorizationEndDate: '2025-08-14',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2025-01-14').toISOString(),
        updatedAt: new Date('2025-01-14').toISOString(),
      },
      {
        id: 'claim_med_15',
        category: 'medications',
        rxNumber: 'RX-10440',
        productName: 'Metoprolol 50mg',
        prescriberName: 'Dr. A. Johnson',
        prescriberLicense: 'CPSO #87921',
        prescriberFax: '+1 (416) 555-1234',
        prescriberPhone: '+1 (416) 555-5678',
        dateOfPrescription: '2024-12-28',
        type: 'renewal',
        claimStatus: 'authorized',
        authorizationNumber: 'E-67890',
        authorizationStartDate: '2024-12-28',
        authorizationEndDate: '2025-06-28',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2024-12-28').toISOString(),
        updatedAt: new Date('2024-12-28').toISOString(),
      },
      {
        id: 'claim_med_16',
        category: 'medications',
        rxNumber: 'RX-10441',
        productName: 'Albuterol Inhaler',
        prescriberName: 'Dr. H. Lee',
        prescriberLicense: 'CPSO #54321',
        prescriberFax: '+1 (416) 555-7777',
        prescriberPhone: '+1 (416) 555-8888',
        dateOfPrescription: '2025-01-15',
        type: 'new',
        claimStatus: 'new',
        authorizationNumber: '',
        authorizationStartDate: '',
        authorizationEndDate: '',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2025-01-15').toISOString(),
        updatedAt: new Date('2025-01-15').toISOString(),
      },
      {
        id: 'claim_med_17',
        category: 'medications',
        rxNumber: 'RX-10442',
        productName: 'Furosemide 40mg',
        prescriberName: 'Dr. I. Chen',
        prescriberLicense: 'CPSO #98765',
        prescriberFax: '+1 (416) 555-9999',
        prescriberPhone: '+1 (416) 555-0000',
        dateOfPrescription: '2025-01-02',
        type: 'renewal',
        claimStatus: 'case-number-open',
        authorizationNumber: '',
        authorizationStartDate: '',
        authorizationEndDate: '',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2025-01-02').toISOString(),
        updatedAt: new Date('2025-01-02').toISOString(),
      },
      {
        id: 'claim_med_18',
        category: 'medications',
        rxNumber: 'RX-10443',
        productName: 'Pantoprazole 40mg',
        prescriberName: 'Dr. B. Smith',
        prescriberLicense: 'CPSO #98765',
        prescriberFax: '',
        prescriberPhone: '+1 (416) 555-9012',
        dateOfPrescription: '2025-01-16',
        type: 'new',
        claimStatus: 'authorized',
        authorizationNumber: 'E-78901',
        authorizationStartDate: '2025-01-16',
        authorizationEndDate: '2025-09-16',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2025-01-16').toISOString(),
        updatedAt: new Date('2025-01-16').toISOString(),
      },
      {
        id: 'claim_med_19',
        category: 'medications',
        rxNumber: 'RX-10444',
        productName: 'Tramadol 50mg',
        prescriberName: 'Dr. J. Patel',
        prescriberLicense: 'CPSO #13579',
        prescriberFax: '+1 (416) 555-1112',
        prescriberPhone: '+1 (416) 555-2223',
        dateOfPrescription: '2024-12-30',
        type: 'prior-authorization',
        claimStatus: 'new',
        authorizationNumber: '',
        authorizationStartDate: '',
        authorizationEndDate: '',
        documents: [],
        notes: [],
        priority: true,
        createdAt: new Date('2024-12-30').toISOString(),
        updatedAt: new Date('2024-12-30').toISOString(),
      },
      {
        id: 'claim_med_20',
        category: 'medications',
        rxNumber: 'RX-10445',
        productName: 'Sertraline 50mg',
        prescriberName: 'Dr. K. Singh',
        prescriberLicense: 'CPSO #24680',
        prescriberFax: '+1 (416) 555-3334',
        prescriberPhone: '+1 (416) 555-4445',
        dateOfPrescription: '2025-01-01',
        type: 'renewal',
        claimStatus: 'authorized',
        authorizationNumber: 'E-89012',
        authorizationStartDate: '2025-01-01',
        authorizationEndDate: '2025-07-01',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2025-01-01').toISOString(),
        updatedAt: new Date('2025-01-01').toISOString(),
      },
      {
        id: 'claim_med_21',
        category: 'medications',
        rxNumber: 'RX-10446',
        productName: 'Warfarin 2mg',
        prescriberName: 'Dr. A. Johnson',
        prescriberLicense: 'CPSO #87921',
        prescriberFax: '+1 (416) 555-1234',
        prescriberPhone: '+1 (416) 555-5678',
        dateOfPrescription: '2025-01-17',
        type: 'new',
        claimStatus: 'case-number-open',
        authorizationNumber: '',
        authorizationStartDate: '',
        authorizationEndDate: '',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2025-01-17').toISOString(),
        updatedAt: new Date('2025-01-17').toISOString(),
      },
      {
        id: 'claim_med_22',
        category: 'medications',
        rxNumber: 'RX-10447',
        productName: 'Clopidogrel 75mg',
        prescriberName: 'Dr. L. Thompson',
        prescriberLicense: 'CPSO #36914',
        prescriberFax: '+1 (416) 555-5556',
        prescriberPhone: '+1 (416) 555-6667',
        dateOfPrescription: '2025-01-18',
        type: 'renewal',
        claimStatus: 'new',
        authorizationNumber: '',
        authorizationStartDate: '',
        authorizationEndDate: '',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2025-01-18').toISOString(),
        updatedAt: new Date('2025-01-18').toISOString(),
      },
      {
        id: 'claim_med_23',
        category: 'medications',
        rxNumber: 'RX-10448',
        productName: 'Citalopram 20mg',
        prescriberName: 'Dr. M. Anderson',
        prescriberLicense: 'CPSO #47026',
        prescriberFax: '+1 (416) 555-7778',
        prescriberPhone: '+1 (416) 555-8889',
        dateOfPrescription: '2024-12-29',
        type: 'prior-authorization',
        claimStatus: 'authorized',
        authorizationNumber: 'E-90123',
        authorizationStartDate: '2024-12-29',
        authorizationEndDate: '2025-08-29',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2024-12-29').toISOString(),
        updatedAt: new Date('2024-12-29').toISOString(),
      },
      {
        id: 'claim_med_24',
        category: 'medications',
        rxNumber: 'RX-10449',
        productName: 'Digoxin 0.25mg',
        prescriberName: 'Dr. N. Wilson',
        prescriberLicense: 'CPSO #58137',
        prescriberFax: '+1 (416) 555-9990',
        prescriberPhone: '+1 (416) 555-0001',
        dateOfPrescription: '2025-01-19',
        type: 'new',
        claimStatus: 'authorized',
        authorizationNumber: 'E-01234',
        authorizationStartDate: '2025-01-19',
        authorizationEndDate: '2025-10-19',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2025-01-19').toISOString(),
        updatedAt: new Date('2025-01-19').toISOString(),
      },
      {
        id: 'claim_med_25',
        category: 'medications',
        rxNumber: 'RX-10450',
        productName: 'Venlafaxine 75mg',
        prescriberName: 'Dr. O. Taylor',
        prescriberLicense: 'CPSO #69248',
        prescriberFax: '+1 (416) 555-1113',
        prescriberPhone: '+1 (416) 555-2224',
        dateOfPrescription: '2024-12-27',
        type: 'renewal',
        claimStatus: 'new',
        authorizationNumber: '',
        authorizationStartDate: '',
        authorizationEndDate: '',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2024-12-27').toISOString(),
        updatedAt: new Date('2024-12-27').toISOString(),
      },
      {
        id: 'claim_med_26',
        category: 'medications',
        rxNumber: 'RX-10451',
        productName: 'Duloxetine 60mg',
        prescriberName: 'Dr. B. Smith',
        prescriberLicense: 'CPSO #98765',
        prescriberFax: '',
        prescriberPhone: '+1 (416) 555-9012',
        dateOfPrescription: '2025-01-20',
        type: 'new',
        claimStatus: 'case-number-open',
        authorizationNumber: '',
        authorizationStartDate: '',
        authorizationEndDate: '',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2025-01-20').toISOString(),
        updatedAt: new Date('2025-01-20').toISOString(),
      },
      {
        id: 'claim_med_27',
        category: 'medications',
        rxNumber: 'RX-10452',
        productName: 'Quetiapine 100mg',
        prescriberName: 'Dr. P. Jackson',
        prescriberLicense: 'CPSO #70359',
        prescriberFax: '+1 (416) 555-3335',
        prescriberPhone: '+1 (416) 555-4446',
        dateOfPrescription: '2025-01-21',
        type: 'prior-authorization',
        claimStatus: 'authorized',
        authorizationNumber: 'E-12340',
        authorizationStartDate: '2025-01-21',
        authorizationEndDate: '2025-11-21',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2025-01-21').toISOString(),
        updatedAt: new Date('2025-01-21').toISOString(),
      },
      {
        id: 'claim_med_28',
        category: 'medications',
        rxNumber: 'RX-10453',
        productName: 'Ramipril 5mg',
        prescriberName: 'Dr. A. Johnson',
        prescriberLicense: 'CPSO #87921',
        prescriberFax: '+1 (416) 555-1234',
        prescriberPhone: '+1 (416) 555-5678',
        dateOfPrescription: '2024-12-26',
        type: 'renewal',
        claimStatus: 'new',
        authorizationNumber: '',
        authorizationStartDate: '',
        authorizationEndDate: '',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2024-12-26').toISOString(),
        updatedAt: new Date('2024-12-26').toISOString(),
      },
      {
        id: 'claim_med_29',
        category: 'medications',
        rxNumber: 'RX-10454',
        productName: 'Allopurinol 300mg',
        prescriberName: 'Dr. Q. White',
        prescriberLicense: 'CPSO #81470',
        prescriberFax: '+1 (416) 555-5557',
        prescriberPhone: '+1 (416) 555-6668',
        dateOfPrescription: '2025-01-22',
        type: 'new',
        claimStatus: 'case-number-open',
        authorizationNumber: '',
        authorizationStartDate: '',
        authorizationEndDate: '',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2025-01-22').toISOString(),
        updatedAt: new Date('2025-01-22').toISOString(),
      },
      {
        id: 'claim_med_30',
        category: 'medications',
        rxNumber: 'RX-10455',
        productName: 'Prednisone 10mg',
        prescriberName: 'Dr. R. Harris',
        prescriberLicense: 'CPSO #92581',
        prescriberFax: '+1 (416) 555-7779',
        prescriberPhone: '+1 (416) 555-8890',
        dateOfPrescription: '2024-12-25',
        type: 'renewal',
        claimStatus: 'authorized',
        authorizationNumber: 'E-23450',
        authorizationStartDate: '2024-12-25',
        authorizationEndDate: '2025-06-25',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2024-12-25').toISOString(),
        updatedAt: new Date('2024-12-25').toISOString(),
      },
      // Appeals - Sample data with new fields
      {
        id: 'claim_appeal_1',
        category: 'appeals',
        rxNumber: 'AP-5001',
        productName: 'Ozempic 0.5mg Pen',
        prescriberName: 'Dr. C. Williams',
        prescriberLicense: 'CPSO #45678',
        prescriberFax: '+1 (416) 555-3456',
        prescriberPhone: 'DIN-02184476',
        dateOfPrescription: '2024-01-10',
        type: 'new',
        claimStatus: 'new',
        authorizationNumber: '',
        authorizationStartDate: '',
        authorizationEndDate: '',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2024-01-10').toISOString(),
        updatedAt: new Date('2024-01-10').toISOString(),
      },
      {
        id: 'claim_appeal_2',
        category: 'appeals',
        rxNumber: 'AP-5002',
        productName: 'Wegovy 0.25mg Pen',
        prescriberName: 'Dr. A. Martinez',
        prescriberLicense: 'CPSO #56789',
        prescriberFax: '+1 (416) 555-4567',
        prescriberPhone: 'DIN-02345678',
        dateOfPrescription: '2024-01-15',
        type: 'new',
        claimStatus: 'patient-signed-letter',
        authorizationNumber: '',
        authorizationStartDate: '',
        authorizationEndDate: '',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2024-01-15').toISOString(),
        updatedAt: new Date('2024-01-20').toISOString(),
      },
      {
        id: 'claim_appeal_3',
        category: 'appeals',
        rxNumber: 'AP-5003',
        productName: 'Mounjaro 5mg Pen',
        prescriberName: 'Dr. B. Thompson',
        prescriberLicense: 'CPSO #67890',
        prescriberFax: '+1 (416) 555-5678',
        prescriberPhone: 'DIN-02456789',
        dateOfPrescription: '2024-01-20',
        type: 'new',
        claimStatus: 'letter-sent-to-doctor',
        authorizationNumber: '',
        authorizationStartDate: '',
        authorizationEndDate: '',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2024-01-20').toISOString(),
        updatedAt: new Date('2024-01-22').toISOString(),
      },
      {
        id: 'claim_appeal_4',
        category: 'appeals',
        rxNumber: 'AP-5004',
        productName: 'Humira 40mg Pen',
        prescriberName: 'Dr. L. Garcia',
        prescriberLicense: 'CPSO #78901',
        prescriberFax: '+1 (416) 555-6789',
        prescriberPhone: 'DIN-02567890',
        dateOfPrescription: '2024-01-25',
        type: 'new',
        claimStatus: 'awaiting-answer',
        authorizationNumber: '',
        authorizationStartDate: '',
        authorizationEndDate: '',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2024-01-25').toISOString(),
        updatedAt: new Date('2024-01-28').toISOString(),
      },
      {
        id: 'claim_appeal_5',
        category: 'appeals',
        rxNumber: 'AP-5005',
        productName: 'Trulicity 1.5mg Pen',
        prescriberName: 'Dr. M. Rodriguez',
        prescriberLicense: 'CPSO #89012',
        prescriberFax: '+1 (416) 555-7890',
        prescriberPhone: 'DIN-02678901',
        dateOfPrescription: '2024-02-01',
        type: 'new',
        claimStatus: 'authorized',
        authorizationNumber: 'E-AP-12345',
        authorizationStartDate: '',
        authorizationEndDate: '2025-02-01',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2024-02-01').toISOString(),
        updatedAt: new Date('2024-02-10').toISOString(),
      },
      {
        id: 'claim_appeal_6',
        category: 'appeals',
        rxNumber: 'AP-5006',
        productName: 'Stelara 90mg/mL',
        prescriberName: 'Dr. N. Lee',
        prescriberLicense: 'CPSO #90123',
        prescriberFax: '+1 (416) 555-8901',
        prescriberPhone: 'DIN-02789012',
        dateOfPrescription: '2024-02-05',
        type: 'new',
        claimStatus: 'denied',
        authorizationNumber: '',
        authorizationStartDate: '',
        authorizationEndDate: '',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2024-02-05').toISOString(),
        updatedAt: new Date('2024-02-08').toISOString(),
      },
      // Manual Claims - Sample data
      {
        id: 'claim_manual_1',
        category: 'manual-claims',
        rxNumber: 'MC-2001',
        productName: 'Humalog KwikPen 100u/ml',
        prescriberName: 'Dr. D. Brown',
        prescriberLicense: 'CPSO #23456',
        prescriberFax: '',
        prescriberPhone: '+1 (416) 555-7890',
        dateOfPrescription: '2024-01-25',
        type: 'renewal',
        claimStatus: 'case-number-open',
        authorizationNumber: 'E-98765',
        authorizationStartDate: '2024-01-25',
        authorizationEndDate: '2024-06-30',
        documents: [],
        notes: [
          {
            id: 'note_2',
            text: 'Authorization expiring soon - need renewal',
            staffUsername: 'Admin User',
            timestamp: new Date('2024-01-25').toISOString(),
          },
        ],
        priority: false,
        createdAt: new Date('2024-01-25').toISOString(),
        updatedAt: new Date('2024-01-25').toISOString(),
      },
      // Diapers & Pads - Sample data
      {
        id: 'claim_diapers_1',
        category: 'diapers-pads',
        rxNumber: 'DP-3001',
        productName: 'Huggies Size 3',
        prescriberName: 'Dr. E. Davis',
        prescriberLicense: 'CPSO #11223',
        prescriberFax: '+1 (416) 555-2468',
        prescriberPhone: '+1 (416) 555-1357',
        dateOfPrescription: '2024-01-18',
        type: 'new',
        claimStatus: 'authorized',
        authorizationNumber: 'E-11111',
        authorizationStartDate: '2024-01-18',
        authorizationEndDate: '2024-12-31',
        documents: [],
        notes: [],
        priority: false,
        createdAt: new Date('2024-01-18').toISOString(),
        updatedAt: new Date('2024-01-18').toISOString(),
      },
    ];

    // Delete existing claims
    await collection.deleteMany({});

    // Insert dummy claims
    await collection.insertMany(dummyClaims);

    return NextResponse.json({
      success: true,
      message: `Successfully seeded ${dummyClaims.length} dummy claims`,
      claims: dummyClaims,
    });
  } catch (error) {
    console.error('Error seeding claims:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to seed claims' },
      { status: 500 }
    );
  }
}

export async function GET() {
  try {
    const collection = await getCollection('claims');
    const count = await collection.countDocuments({});

    return NextResponse.json({
      success: true,
      count,
    });
  } catch (error) {
    console.error('Error counting claims:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to count claims' },
      { status: 500 }
    );
  }
}
