import nodemailer from 'nodemailer';
import { IOrder } from '../models/Order';

// Create transporter
const createTransporter = () => {
  return nodemailer.createTransport({
    host: process.env.EMAIL_SERVER,
    port: 587,
    secure: false, // true for 465, false for other ports
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });
};

export const sendOrderNotification = async (order: IOrder): Promise<void> => {
  try {
    const transporter = createTransporter();
    const adminEmail = process.env.ADMIN_EMAIL;

    if (!adminEmail) {
      throw new Error('ADMIN_EMAIL environment variable is not set');
    }

    const mailOptions = {
      from: process.env.EMAIL_USER,
      to: adminEmail,
      subject: `New Order from ${order.fullName} - Kateri Pharmacy`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #2563eb;">New Order Received</h2>
          
          <div style="background-color: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="color: #1e40af; margin-top: 0;">Order Details</h3>
            
            <p><strong>Full Name:</strong> ${order.fullName}</p>
            <p><strong>Email:</strong> ${order.email}</p>
            ${order.phone ? `<p><strong>Phone:</strong> ${order.phone}</p>` : ''}
            ${order.address ? `<p><strong>Address:</strong> ${order.address}</p>` : ''}
            ${order.message ? `<p><strong>Message:</strong> ${order.message}</p>` : ''}
            ${order.prescription ? `<p><strong>Prescription:</strong> <a href="${order.prescription}" target="_blank">View Prescription</a></p>` : ''}
            
            <p><strong>Order Date:</strong> ${order.createdAt?.toLocaleString()}</p>
            <p><strong>Order ID:</strong> ${order._id}</p>
          </div>
          
          <div style="background-color: #fef3c7; padding: 15px; border-radius: 8px; border-left: 4px solid #f59e0b;">
            <p style="margin: 0; color: #92400e;">
              <strong>Action Required:</strong> Please review this order and contact the customer to confirm details and arrange pickup/delivery.
            </p>
          </div>
          
          <hr style="margin: 30px 0; border: none; border-top: 1px solid #e5e7eb;">
          
          <p style="color: #6b7280; font-size: 14px;">
            This email was automatically generated by the Kateri Pharmacy system.
          </p>
        </div>
      `,
      text: `
        New Order from ${order.fullName}
        
        Order Details:
        - Full Name: ${order.fullName}
        - Email: ${order.email}
        ${order.phone ? `- Phone: ${order.phone}` : ''}
        ${order.address ? `- Address: ${order.address}` : ''}
        ${order.message ? `- Message: ${order.message}` : ''}
        ${order.prescription ? `- Prescription: ${order.prescription}` : ''}
        
        Order Date: ${order.createdAt?.toLocaleString()}
        Order ID: ${order._id}
        
        Please review this order and contact the customer to confirm details.
      `
    };

    await transporter.sendMail(mailOptions);
    console.log('Order notification email sent successfully');

  } catch (error) {
    console.error('Error sending order notification email:', error);
    throw error;
  }
};

export const sendOrderConfirmation = async (order: IOrder): Promise<void> => {
  try {
    const transporter = createTransporter();

    const mailOptions = {
      from: process.env.EMAIL_USER,
      to: order.email,
      subject: 'Order Confirmation - Kateri Pharmacy',
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #2563eb;">Order Confirmation</h2>
          
          <p>Dear ${order.fullName},</p>
          
          <p>Thank you for your order! We have received your request and will contact you shortly to confirm the details and arrange pickup or delivery.</p>
          
          <div style="background-color: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="color: #1e40af; margin-top: 0;">Your Order Details</h3>
            
            <p><strong>Order ID:</strong> ${order._id}</p>
            <p><strong>Order Date:</strong> ${order.createdAt?.toLocaleString()}</p>
            ${order.message ? `<p><strong>Your Message:</strong> ${order.message}</p>` : ''}
            ${order.prescription ? `<p><strong>Prescription:</strong> Received</p>` : ''}
          </div>
          
          <p>We will contact you at <strong>${order.email}</strong>${order.phone ? ` or <strong>${order.phone}</strong>` : ''} to confirm your order.</p>
          
          <p>Thank you for choosing Kateri Pharmacy!</p>
          
          <hr style="margin: 30px 0; border: none; border-top: 1px solid #e5e7eb;">
          
          <p style="color: #6b7280; font-size: 14px;">
            Kateri Pharmacy<br>
            This is an automated confirmation email.
          </p>
        </div>
      `
    };

    await transporter.sendMail(mailOptions);
    console.log('Order confirmation email sent successfully');

  } catch (error) {
    console.error('Error sending order confirmation email:', error);
    throw error;
  }
};
